In [1]:
import numpy as np

def gram_schmidt(A):
    """
    Applies the Gram-Schmidt method to matrix A to 
    orthogonalize its rows.
    
    Args:
    - A (numpy.ndarray): The matrix to be orthogonalized.
    
    Returns:
    - Q (numpy.ndarray): The orthogonalized matrix.
    """
    m, n = A.shape
    Q = np.zeros((m, n))
    
    for j in range(n):
        # Start with the j-th column of A
        v = A[:, j]
        
        for i in range(j):
            # Subtract the projection of A[:, j] 
            # onto the i-th column of Q
            v = v - np.dot(Q[:, i], A[:, j]) * Q[:, i] 
        # Normalize the resulting vector
        Q[:, j] = v / np.linalg.norm(v)
    return Q

def are_rows_orthogonal(Q):
    """
    Verify if the column of matrix Q are orthogonal.
    
    Args:
    - Q (numpy.ndarray): The matrix to be verified.
    
    Returns:
    - bool: True if the rows of Q are orthogonal, False otherwise.
    """
    m, n = Q.shape
    for i in range(n):
        for j in range(n):
            dot_product = np.dot(Q[:, i], Q[:,j])
            # Check if the dot product of 
            #different column is close to 0
            if i != j and not np.isclose(dot_product, 0):
                return False
            # Check if the dot product of the 
            #same row with itself is close to 1
            elif i == j and not np.isclose(dot_product, 1):
                return False    
    return True

# Example matrix
A = np.array([[6, 2, 1], 
              [2, 3, 1], 
              [1, 1, 1]])
print(A[:,0])
# Orthogonalize the matrix A
Q = gram_schmidt(A)
print("Orthogonalized Matrix Q:\n", Q)

# Verify if the matrix Q is orthogonal
print("Is Q orthogonal?", are_rows_orthogonal(Q))

# Perform QR decomposition to obtain the orthogonal matrix Q
Q, R = np.linalg.qr(A)

print("Orthogonal matrix Q:")
print(Q)

[6 2 1]
Orthogonalized Matrix Q:
 [[ 0.93704257 -0.34242719 -0.06851887]
 [ 0.31234752  0.90957224 -0.27407548]
 [ 0.15617376  0.2354187   0.95926419]]
Is Q orthogonal? True
Orthogonal matrix Q:
[[-0.93704257  0.34242719 -0.06851887]
 [-0.31234752 -0.90957224 -0.27407548]
 [-0.15617376 -0.2354187   0.95926419]]


In [3]:
import numpy as np

def QR(A):
    """
    Perform QR decomposition of matrix A 
    using Gram-Schmidt process.
    Parameters:
    A (numpy.ndarray): The input matrix.

    Returns:
    Q (numpy.ndarray): Orthogonal matrix.
    R (numpy.ndarray): Upper triangular matrix.
    """
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R

# Usage
A = np.array([[6, 2, 1], [2, 3, 1], [1, 1, 1]])
Q, R = QR(A)

print('Q:\n', Q)
print('R:\n', R)
print(np.dot(Q,R))
Q, R = np.linalg.qr(A)

print('Q:\n', Q)
print('R:\n', R)
print(np.dot(Q,R))

Q:
 [[ 0.93704257 -0.34242719 -0.06851887]
 [ 0.31234752  0.90957224 -0.27407548]
 [ 0.15617376  0.2354187   0.95926419]]
R:
 [[6.40312424 2.96730148 1.40556386]
 [0.         2.27928102 0.80256374]
 [0.         0.         0.61666984]]
[[6. 2. 1.]
 [2. 3. 1.]
 [1. 1. 1.]]
Q:
 [[-0.93704257  0.34242719 -0.06851887]
 [-0.31234752 -0.90957224 -0.27407548]
 [-0.15617376 -0.2354187   0.95926419]]
R:
 [[-6.40312424 -2.96730148 -1.40556386]
 [ 0.         -2.27928102 -0.80256374]
 [ 0.          0.          0.61666984]]
[[6. 2. 1.]
 [2. 3. 1.]
 [1. 1. 1.]]


In [7]:
import numpy as np

def QRdecompose(Ai):
    """
    Perform QR decomposition using the Gram-Schmidt process.
    
    Parameters:
    - A: Input matrix to be decomposed (numpy array)
    
    Returns:
    - Q: Orthogonal matrix (numpy array)
    - R: Upper triangular matrix (numpy array)
    """
    A=np.copy(Ai)
    n = A.shape[0]
    Q = np.zeros((n, n))
    R = np.zeros((n, n))
    
    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
    return Q, R
def qrdec(A):
    n = A.shape[0]
    Ap = np.copy(A)
    Q = np.zeros((n,n))
    R = np.zeros((n,n))
    for j in range(n):
        for i in range(j):
            R[i,j] = Q[:,i]@A[:,j]
            Q[:,j] =A[:,j]- R[i,j]*Q[:,i]
            A[:,j] =- R[i,j]*Q[:,i]

        R[j,j] = mag(Ap[:,j])
        Q[:,j] = Ap[:,j]/R[j,j]
    return Q, R

# Example usage:
A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])
Q, R = QRdecompose(A)

print("Matrix Q:\n", Q)
print(are_rows_orthogonal(Q))
print("\nMatrix R:\n", R)

Matrix Q:
 [[ 0.85714286 -0.39428571 -0.33142857]
 [ 0.42857143  0.90285714  0.03428571]
 [-0.28571429  0.17142857 -0.94285714]]
True

Matrix R:
 [[ 14.  21. -14.]
 [  0. 175. -70.]
 [  0.   0.  35.]]
