# Power method

In [5]:
import numpy as np
A = np.array([
    [6, 2, 1, 3],
    [2, 3, 1, 1],
    [1, 1, 5, 2],
    [3, 1, 2, 7]])
x = np.random.rand(A.shape[1])
help(np.random.rand)
print(x)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [2]:
# Author: Junfei Ding, Guizhou University, Date: 2023-11-13
import numpy as np
def powerA(A, k=50, tol=1e-6):
    # Randomly initialize a vector
    x = np.random.rand(A.shape[1])
    # Normalize the initial vector
    x = x / np.linalg.norm(x)
    # Initialize eigenvalue to zero
    lambda_old = 0
    for i in range(k):
        # Matrix-vector multiplication
        Ax = np.dot(A, x)
        # Normalize the vector
        x = Ax / np.linalg.norm(Ax)
        # Calculate the Rayleigh quotient for eigenvalue estimation
        lambda_new = np.dot(x.T, Ax)
        # Check for convergence
        if np.abs(lambda_new - lambda_old) < tol:
            return lambda_new, x
        lambda_old = lambda_new
    # If not converged within max_iterations
    print("Didn't converge within the specified number of iterations.")
    return lambda_new, x
if __name__=="__main__":
    # Example with a 4x4 matrix
    A = np.array([
        [6, 2, 1, 3],
        [2, 3, 1, 1],
        [1, 1, 5, 2],
        [3, 1, 2, 7]])
    eigval, eigvec = powerA(A)
    print("Dominant Eigenvalue and Eigenvector calculated by power method: ")
    print(eigval,eigvec)
    print("By numpy: ", )
    npeigvals, npeigvecs = np.linalg.eig(A)
    print(npeigvals[0],npeigvecs[:,0])

Dominant Eigenvalue and Eigenvector calculated by power method: 
11.059043359690929 [0.5804173  0.27300788 0.36378746 0.67545625]
By numpy: 
11.059043413934548 [0.58038993 0.27299305 0.36380855 0.6754744 ]


# Inverse power method
- 求矩阵的最小特征值和特征向量
- $x^{(k)}=A^{-1}x^{(k-1)}$
- $Ax^{(k)}=x^{(k-1)}$

In [3]:
import numpy as np

def inverse_power_method(A, tol=1e-10, max_iter=1000):
    x0= np.random.rand(A.shape[1])
    x=x0/np.linalg.norm(x0)
    lambda_old=0
    for i in range(max_iter):             
        # Solve Ay = x for y
        y = np.linalg.solve(A, x)
        x = y / np.linalg.norm(y)
        # Rayleigh quotient iteration to approximate the eigenvalue
        lambda_min = np.dot(x.T, np.dot(A, x)) / np.dot(x.T, x)
        # Check for convergence
        if (lambda_min-lambda_old) < tol:
            return lambda_min, x
        lambda_old=lambda_min
    # If not converged within max_iterations
    print("Power Method did not converge within the specified number of iterations.")
    return lambda_min, x

# Usage
A = np.array([
    [6, 2, 1, 3],
    [2, 3, 1, 1],
    [1, 1, 5, 2],
    [3, 1, 2, 7]
])
eigenvalue, eigenvector = inverse_power_method(A)

print('Eigenvalue:', eigenvalue)
print('Eigenvector:', eigenvector)

Eigenvalue: 2.000093610852924
Eigenvector: [-0.41642485  0.90185879  0.00631924  0.1148962 ]


In [1]:
import numpy as np

def power_method_with_rayleigh(A, max_iterations=1000, tol=1e-6):
    """
    Estimate the dominant eigenvalue and corresponding eigenvector of a matrix using the Power Method 
    with the Rayleigh quotient for improved accuracy.
    
    Parameters:
    - A (numpy.ndarray): A square matrix for which the dominant eigenvalue and eigenvector are to be estimated.
    - max_iterations (int): The maximum number of iterations to perform. Default is 1000.
    - tol (float): The tolerance for convergence. If the change in the Rayleigh quotient between iterations 
      is less than this value, the function returns the current estimates. Default is 1e-6.

    Returns:
    - lambda_new (float): The estimated dominant eigenvalue of the matrix.
    - x (numpy.ndarray): The estimated eigenvector corresponding to the dominant eigenvalue. 

    Note:
    The function prints a message and returns the current estimates if the specified number of 
    max_iterations is reached without convergence.
    """
    
    # Randomly initialize a vector
    x = np.random.rand(A.shape[1])
    
    # Normalize the initial vector
    x = x / np.linalg.norm(x)
    
    # Initialize eigenvalue to zero
    lambda_old = 0
    
    for i in range(max_iterations):
        # Matrix-vector multiplication
        Ax = np.dot(A, x)
        
        # Calculate the Rayleigh quotient for eigenvalue estimation
        lambda_new = np.dot(x.T, Ax) / np.dot(x.T, x)
        
        # Normalize the vector
        x = Ax / np.linalg.norm(Ax)
        
        # Check for convergence
        if np.abs(lambda_new - lambda_old) < tol:
            return lambda_new, x
        
        lambda_old = lambda_new

    # If not converged within max_iterations
    print("Power Method did not converge within the specified number of iterations.")
    return lambda_new, x

# Example with a 4x4 matrix
A = np.array([
    [6, 2, 1, 3],
    [2, 3, 1, 1],
    [1, 1, 5, 2],
    [3, 1, 2, 7]
])
eigenvalue, eigenvector = power_method_with_rayleigh(A)
print("Dominant Eigenvalue:", eigenvalue)
print("Dominant Eigenvector:", eigenvector)
npeigvals, npeigvecs = np.linalg.eig(A)
indx=0
print(" ")
print(npeigvals[indx]); print(npeigvecs[:,indx])
help(power_method_with_rayleigh)

Dominant Eigenvalue: 11.059043310947498
Dominant Eigenvector: [0.5803596  0.2729834  0.36384598 0.6754842 ]
 
11.059043413934548
[0.58038993 0.27299305 0.36380855 0.6754744 ]
Help on function power_method_with_rayleigh in module __main__:

power_method_with_rayleigh(A, max_iterations=1000, tol=1e-06)
    Estimate the dominant eigenvalue and corresponding eigenvector of a matrix using the Power Method 
    with the Rayleigh quotient for improved accuracy.
    
    Parameters:
    - A (numpy.ndarray): A square matrix for which the dominant eigenvalue and eigenvector are to be estimated.
    - max_iterations (int): The maximum number of iterations to perform. Default is 1000.
    - tol (float): The tolerance for convergence. If the change in the Rayleigh quotient between iterations 
      is less than this value, the function returns the current estimates. Default is 1e-6.
    
    Returns:
    - lambda_new (float): The estimated dominant eigenvalue of the matrix.
    - x (numpy.ndarray):

In [17]:
import numpy as np
def powermethod(A):
    n=A.shape[0]
    x=np.ones(n)
    x=np.linalg.norm(x)
    k=10
    u=0
    for i  in range(k):
        x=np.dot(A,x)
        x=x/np.linalg.norm(x)
        u=x.T@A@x
    return x,u
A = np.array([
    [6, 2, 1, 3],
    [2, 3, 1, 1],
    [1, 1, 5, 2],
    [3, 1, 2, 7]
])
x,u=powermethod(A)
print(x)
print(u)
npeigvals, npeigvecs = np.linalg.eig(A)
print("Numpy u: ",npeigvals[0])
print("Numpy x: ",npeigvecs[0])

[[0.33689288 0.15845645 0.21110341 0.39202367]
 [0.15845645 0.07453282 0.09930643 0.18439048]
 [0.21110341 0.09930643 0.13242419 0.24575207]
 [0.39202367 0.18439048 0.24575207 0.45627752]]
[[3.72526606 1.75222152 2.335126   4.33557118]
 [1.75222152 0.82417745 1.09835324 2.03928553]
 [2.335126   1.09835324 1.46373805 2.71768647]
 [4.33557118 2.03928553 2.71768647 5.04586178]]
Numpy u:  11.059043413934539
Numpy x:  [ 0.58038993  0.48251507 -0.59796432 -0.26975065]


In [1]:
def mag(xs):
    return np.sqrt(np.sum(xs*xs))

def power(A,kmax=6):
    zs = np.ones(A.shape[0])
    qs = zs/mag(zs)
    for k in range(1,kmax):
        zs = A@qs
        qs = zs/mag(zs)
        print(k,qs)

    lam = qs@A@qs
    return lam, qs

In [2]:
import numpy as np

def power_method_with_rayleigh(A, max_iterations=1000, tol=1e-6):
   
    # Randomly initialize a vector
    x = np.random.rand(A.shape[1])
    
    # Normalize the initial vector
    x = x / np.linalg.norm(x)
    
    # Initialize eigenvalue to zero
    lambda_old = 0
    
    for i in range(max_iterations):
        # Matrix-vector multiplication
        Ax = np.dot(A, x)
        
        # Calculate the Rayleigh quotient for eigenvalue estimation
        lambda_new = np.dot(x.T, Ax) / np.dot(x.T, x)
        
        # Normalize the vector
        x = Ax / np.linalg.norm(Ax)
        
        # Check for convergence
        if np.abs(lambda_new - lambda_old) < tol:
            return lambda_new, x
        
        lambda_old = lambda_new

    # If not converged within max_iterations
    print("Power Method did not converge within the specified number of iterations.")
    return lambda_new, x

# Example with a 4x4 matrix
A = np.array([
    [6, 2, 1, 3],
    [2, 3, 1, 1],
    [1, 1, 5, 2],
    [3, 1, 2, 7]
])
eigenvalue, eigenvector = power_method_with_rayleigh(A)
print("Dominant Eigenvalue:", eigenvalue)
print("Dominant Eigenvector:", eigenvector)
npeigvals, npeigvecs = np.linalg.eig(A)
indx=0
print(" ")
print(npeigvals[indx]); print(npeigvecs[:,indx])

Dominant Eigenvalue: 11.059043322015913
Dominant Eigenvector: [0.58036237 0.27298579 0.36384572 0.67548099]
 
11.059043413934548
[0.58038993 0.27299305 0.36380855 0.6754744 ]
