# 1 Forward Substitution

In [2]:
# Author: Junfei Ding, Guizhou University, Date: 2023-10-9
import numpy as np
def forward_substitution(L, b):
    """
    Perform forward substitution to solve
    the lower triangular system Lx = b.
    
    Parameters:
    - L: Lower triangular matrix (2D numpy array)
    - b: Right-hand side vector (1D numpy array)
    
    Returns:
    - x: Solution vector (1D numpy array)
    """
    n = len(b)
    x = np.zeros(n)
    
    for i in range(n):
        x[i] = (b[i] - np.dot(L[i, :i], x[:i])) / L[i, i]
    
    return x
if __name__=="__main__":
    L = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])
    print(L)
    b = np.array([1, 4, 7])
    x=forward_substitution(L,b)
    print(x)

[[1 0 0]
 [2 1 0]
 [3 4 1]]
[ 1.  2. -4.]


# 2 Backward Substitution

In [8]:
# Author: Junfei Ding, Guizhou University, Date: 2023-10-9
import numpy as np
def backward_substitution(U, b):
    """
    Perform backward substitution to solve 
    the upper triangular system Ux = b.
    
    Parameters:
    - U: Upper triangular matrix (2D numpy array)
    - b: Right-hand side vector (1D numpy array)
    
    Returns:
    - x: Solution vector (1D numpy array)
    """
    n = len(b)
    x = np.zeros(n)
    for i in reversed(range(n)):
        x[i]=(b[i]-U[i, i+1:]@x[i+1:])/ U[i, i]
    return x
if __name__=="__main__":
    U = np.array([[1, 2, 3], [0, 1, 4], [0, 0, 1]])
    print(U)
    b = np.array([1, 2, 3])
    x=backward_substitution(U,b)
    print(x)
    help(backward_substitution)

[[1 2 3]
 [0 1 4]
 [0 0 1]]
[ 12. -10.   3.]
Help on function backward_substitution in module __main__:

backward_substitution(U, b)
    Perform backward substitution to solve 
    the upper triangular system Ux = b.
    
    Parameters:
    - U: Upper triangular matrix (2D numpy array)
    - b: Right-hand side vector (1D numpy array)
    
    Returns:
    - x: Solution vector (1D numpy array)



# 3 Gaussian Elimination

In [1]:
import numpy as np
def gaussian_elimination(Ai, bi):
    """
    Solve system of linear equations using 
    Gaussian Elimination without pivoting.
    
    Parameters:
    A (np.array): Coefficient matrix of size (n, n).
    b (np.array): Vector of constant terms of size (n, ).
    
    Returns:
    np.array: Solution vector of size (n, ).
    """
    b=np.copy(bi)
    A=np.copy(Ai)
    n = len(b)

    # Forward elimination
    for i in range(n):
        
        # Zero out below current row
        for k in range(i+1, n):
            coeff = A[k][i] / A[i][i]
            b[k] -= coeff * b[i]
            A[k,i:]-=coeff * A[i,i:]
    # Backward substitution
    x=np.zeros(n)
    for i in reversed(range(n)):
        x[i]=(b[i]-A[i, i+1:] @ x[i+1:])/ A[i, i]
    return x
if __name__=="__main__":
    A = np.array([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]], dtype=float)
    b = np.array([8, -11, -3], dtype=float)
    x = gaussian_elimination(A, b)
    print(A)
    print("Solution:", x)
    x=np.linalg.solve(A,b)
    print("Numpy: ",x)

[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]
Solution: [ 2.  3. -1.]
Numpy:  [ 2.  3. -1.]


# 4 LU decompose

In [1]:
# Author: Junfei Ding, Guizhou University, Date: 2023-10-9
import numpy as np
def lu_decomposition(A):
    """
    Perform LU decomposition on matrix A using numpy slicing.
    
    Parameters:
    A (np.array): Square matrix of size (n, n).
    
    Returns:
    L (np.array): Lower triangular matrix of size (n, n).
    U (np.array): Upper triangular matrix of size (n, n).
    """
    n = A.shape[0]
    L = np.eye(n)
    U = np.copy(A)
    
    for i in range(n):
        for j in range(i+1, n):
            coeff=U[j, i] / U[i, i]
            L[j, i] = coeff
            U[j, i:] -= coeff * U[i, i:]
    
    return L, U
if __name__=="__main__":
    A = np.array([[3, 2, 1], [2, 3, 1], [1, 2, 3]], dtype=float)
    L, U = lu_decomposition(A)
    print("A matix:\n",A)
    print("Lower matix:\n",L)
    print("Upper matix:\n",U)

A matix:
 [[3. 2. 1.]
 [2. 3. 1.]
 [1. 2. 3.]]
Lower matix:
 [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]
Upper matix:
 [[3.         2.         1.        ]
 [0.         1.66666667 0.33333333]
 [0.         0.         2.4       ]]


In [2]:
# Author: Junfei Ding, Guizhou University, Date: 2023-10-9
import numpy as np
def lu_decomposition(A):
    """
    Perform LU decomposition on matrix A using numpy slicing.
    
    Parameters:
    A (np.array): Square matrix of size (n, n).
    
    Returns:
    L (np.array): Lower triangular matrix of size (n, n).
    U (np.array): Upper triangular matrix of size (n, n).
    """
    n = A.shape[0]
    L = np.eye(n)
    U = np.copy(A)
    
    for i in range(n):
        for j in range(i+1, n):
            coeff=U[j, i] / U[i, i]
            L[j, i] = coeff
            U[j, i:] -= coeff * U[i, i:]
    
    return L, U


L, U = lu_decomposition(A)
    
def lu_solve(L, U, b):
    """
    Solve the system of linear equations Ax = b using LU decomposition and numpy slicing.
    
    Parameters:
    L (np.array): Lower triangular matrix of size (n, n).
    U (np.array): Upper triangular matrix of size (n, n).
    b (np.array): Vector of constant terms of size (n, ).
    
    Returns:
    x (np.array): Solution vector of size (n, ).
    """
    n = len(b)
    y = np.zeros(n)
    x = np.zeros(n)
    
    # Forward substitution for Ly = b
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    
    # Backward substitution for Ux = y
    for i in reversed(range(n)):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    
    return x

# Example usage
A = np.array([[3, 2, 1], [2, 3, 1], [1, 2, 3]], dtype=float)
b = np.array([39, 34, 26], dtype=float)

L, U = lu_decomposition(A)
x = lu_solve(L, U, b)
print("Solution:", x)
x=np.linalg.solve(A,b)
print('numpy: ',x)

Solution: [9.25 4.25 2.75]
numpy:  [9.25 4.25 2.75]


# 3 Gaussian Pivot

In [3]:
# Author: Junfei Ding, Guizhou University, Date: 2023-10-9
import numpy as np
def gaussian_pivot(Ai, bi):
    """
    Solve system of linear equations using 
    Gaussian Elimination with pivoting.
    
    Parameters:
    Ai (np.array): Coefficient matrix of size (n, n).
    bi (np.array): Vector of constant terms of size (n, ).
    
    Returns:
    np.array: Solution vector of size (n, ).
    """
    b=np.copy(bi)
    A=np.copy(Ai)
    n = len(b)
    # Forward elimination
    for i in range(n):
        max_row = i
        for k in range(i+1, n):
            if abs(A[k][i]) > abs(A[max_row][i]):
                max_row = k
                # Swap rows for pivot
#         A[[i, max_row]] = A[[max_row, i]]
#         b[i], b[max_row] = b[max_row], b[i]
        # Swap rows for pivot
        A[i,:], A[max_row,:] = A[max_row,:], A[i,:].copy()
        b[i], b[max_row] = b[max_row], b[i]
        # Zero out below current row
        for k in range(i+1, n):
            coeff = A[k][i] / A[i][i]
            b[k] -= coeff * b[i]
            A[k,i:]-=coeff * A[i,i:]
    # Backward substitution
    x=np.zeros(n)
    for i in reversed(range(n)):
        x[i]=(b[i]-np.dot(A[i, i+1:],x[i+1:]))/ A[i, i]
    return x
if __name__=="__main__":
    A = np.array([[2, 1, -1], 
                  [-3, -1, 2], 
                  [-2, 1, 2]], dtype=float)
    b = np.array([8, -11, -3], dtype=float)

    x = gaussian_pivot(A, b)
    print("Solution:", x)
    x=np.linalg.solve(A,b)
    print("Numpy: ",x)

Solution: [ 2.  3. -1.]
Numpy:  [ 2.  3. -1.]
